In [1]:
import torch

In [8]:
torch.manual_seed(0)
torch.rand(2, 10, 5, 5).permute(0, 2, 3, 1)

tensor([[[[0.4963, 0.5529, 0.8198, 0.9412, 0.9704, 0.2036, 0.0321, 0.8163,
           0.5210, 0.7477],
          [0.7682, 0.9527, 0.9971, 0.5995, 0.8369, 0.3748, 0.0780, 0.4423,
           0.8223, 0.1439],
          [0.0885, 0.0362, 0.6984, 0.0652, 0.2820, 0.2564, 0.3986, 0.2768,
           0.1220, 0.3581],
          [0.1320, 0.1852, 0.5675, 0.5460, 0.3742, 0.3251, 0.7742, 0.8998,
           0.1567, 0.3322],
          [0.3074, 0.3734, 0.8352, 0.1872, 0.0237, 0.0902, 0.7703, 0.0960,
           0.2097, 0.4260]],

         [[0.6341, 0.3051, 0.2056, 0.0340, 0.4910, 0.3936, 0.0178, 0.5537,
           0.8500, 0.5055],
          [0.4901, 0.9320, 0.5932, 0.9442, 0.1235, 0.6069, 0.8119, 0.3953,
           0.3203, 0.9124],
          [0.8964, 0.1759, 0.1123, 0.8802, 0.1143, 0.1743, 0.1087, 0.8571,
           0.9217, 0.5624],
          [0.4556, 0.2698, 0.1535, 0.0012, 0.4725, 0.4743, 0.3943, 0.6396,
           0.6808, 0.9478],
          [0.6323, 0.1507, 0.2417, 0.5936, 0.5751, 0.8579, 0.2973, 0.74

In [14]:
embedding = torch.rand(5, 10)
z = torch.rand(2, 10)

In [20]:
torch.sum(z**2, dim=-1, keepdim=True).shape

torch.Size([2, 1])

In [23]:
torch.sum(embedding**2, dim=-1).shape

torch.Size([5])

In [18]:
torch.sum(z**2, dim=-1, keepdim=True) + torch.sum(embedding**2, dim=-1)

tensor([[6.1214, 6.4147, 6.0689, 6.6047, 7.4931],
        [7.8281, 8.1214, 7.7756, 8.3114, 9.1998]])

In [24]:
2*(torch.matmul(z, embedding.T))

tensor([[3.6905, 4.8536, 4.5297, 5.6280, 5.3875],
        [4.1888, 6.4683, 5.3807, 7.1786, 6.5827]])

In [26]:
euclidia_dis = torch.sum(z**2, dim=-1, keepdim=True) + torch.sum(embedding**2, dim=-1) - 2*(torch.matmul(z, embedding.T))
euclidia_dis
## Here the first value tells the euclidean distance between first latent z[0] and first embedding, then first latent -> to second embeddng , then third and so forth
## next row saying , second latent dim z[1] to first, second, third and so forth euclidian distance with embeedding

tensor([[2.4309, 1.5611, 1.5392, 0.9767, 2.1056],
        [3.6393, 1.6531, 2.3949, 1.1328, 2.6171]])

In [30]:
# next we take lowest embedding for each z, by euclidean distance
min_euc_indieces = euclidia_dis.argmin(dim=-1)

In [32]:
# next take the embedding 
embedding[min_euc_indieces]
# the first embedding below is the embedding that is close to first z, the second embedding below for the second z

tensor([[0.0132, 0.2048, 0.3295, 0.7516, 0.1764, 0.9715, 0.3886, 0.4102, 0.8918,
         0.7513],
        [0.0132, 0.2048, 0.3295, 0.7516, 0.1764, 0.9715, 0.3886, 0.4102, 0.8918,
         0.7513]])